BINANCE_API_KEY = "uh01CM97H6ugUTu5ECQhVwxbgNJyFAjbWJASDpuBY8ABVJTpha7DDwgrRUrzNl3s"
BINANCE_SECRET_KEY = "4vTkIS6FLZJuvxGOLgfE7cUS7awUigAwxxk67W94EP4S7cWnN6hXSNuIXSrtTJAI"



TESTNET = True
BINANCE_BASE_URL = "https://demo-api.binance.com/api"